version: '3'
services:
  mongodb:
    image: mongo
    command: --quiet
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
      - default
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  ui-server:
    build:
      context: ./ui-server
    image: genesis-frontend
    ports:
      - "5173:80"

  server:
    build:
      context: ./server
    image: genesis-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/genesis-test
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  mongodb-data: