version: '3'

services:
  mongodb:
    env_file:
      - .env
    image: mongo
    command: --quiet
    container_name: mongodb
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped

  server:
    env_file:
      - .env
    build:
      context: ./server
    image: genesis-backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - DB_LINK=${DB_LINK}
    depends_on:
      - mongodb
    networks:
      - app-network

  ui-server:
    env_file:
      - .env
    depends_on:
      - mongodb
      - server
    build:
      context: ./ui-server
    image: genesis-frontend
    ports:
      - "${UI_PORT}:${UI_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
